apiVersion: v1
kind: Service
metadata:
  name: sale-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 8888
  selector:
    app: my-http-sale